### PR TITLE
Fixed unsupported operations

### LINKED ISSUE #20: Troubles adding to Document Lists
The code gives no errors but when I execute the function I get a console error and my data isn't added to my database. The output of my broadcasts are like this `-170.5,80.5,46.5,EcoGens`. Bellow is what I believe to be all the nessacary info of the issue.

Below is the code causing the error:
https://paste.helpch.at/eqasurebad.sql

Below is the console error:
https://paste.helpch.at/colotedoga.md

Plugin / Server versions:
image

### PR DESCRIPTION
**Pull request by Olyno**
This pull request should fix #20. The main issue is ``Document#getList`` which returns an immutable list, so you can't change it. By casting this list to an ``ArrayList``, you should be able to make changes.

⚠️ This pull request has not been tested due to the lazy developer (me), please be sure there is no problem with it, at your own risks ⚠️

### CODE REVIEW

**Comment by Olyno** [comment]
@EarthAgar can you try this artifact and check if your issue is solved please?

[Download the artifact by clicking here](https://github.com/Romitou/MongoSK/suites/2073855627/artifacts/41955666)

**Comment by EarthAgar** [comment]
No it doesn't fix the issue, here is the error given: https://paste.helpch.at/oyeyefegay.md

By any chance will it ever be possible to set values to locations without having to stringify them?

This artifact also seems to interfere with a condition of mine `if (level of blast protection of event-slot ? 0) < 5:`
image

**Comment by Olyno** [comment]
Well my bad, I didn't expect to get a `null`` from Mongodb's driver. Anyway, can you try the next artifact when github action would let build it without any timeout and report me any other errors please?
@Romitou Please fix github's actions if you can (timeout thing, maybe rerun later?) 🙏🏻

**Comment by EarthAgar** [comment]
I don't quite understand how to do what you want here: `can you try the next artifact when github action would let build it without any timeout`

**Comment by Olyno** [comment]
I simply mean [this artifact](https://github.com/Romitou/MongoSK/suites/2074382101/artifacts/42012138), was waiting the fix of the github action for that

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java [hunk 1]
```diff
@@ -58,13 +59,15 @@ public boolean init(Expression<?>[] exprs, int matchedPattern, Kleenean isDelaye
...
                 return new Object[]{document.get(value)};
             } catch (NullPointerException ex) {
-                return new Object[0]; // That document value doesn't exist;
+                return new Object[0]; // That document value doesn't exist
             }
         } else {
             try {
-                List<Object> list = document.getList(value, Object.class);
-                return (list == null) ? new Object[0] : list.toArray();
+                ArrayList<Object> list = new ArrayList<>(document.getList(value, Object.class));
```
Comment (Romitou) [inline src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:66]: i think we should keep the null check here as the `Document#getList` method can return a null list
i also think that in this case it is not necessary to create an arraylist, what do you think?

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java [hunk 2]
```diff
@@ -94,19 +97,21 @@ public void change(Event e, Object[] delta, Changer.ChangeMode mode) {
                 document.put(value, null);
                 break;
             case ADD:
-                List<Object> addList = document.getList(value, Object.class);
-                if (addList == null) {
-                    document.put(value, deltaList);
-                    return;
+                try {
+                    ArrayList<Object> addList = new ArrayList<>(document.getList(value, Object.class));
```
Comment (Romitou) [inline src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:101]: as stated in my first comment, i think we should check if the list is not null before create an arraylist
since `addList` list can not be in the document, we can simply make a `Document#put` to create the list
```suggestion
                    List<Object> addList = document.getList(value, Object.class);
                    if (addList == null) {
                        document.put(value, deltaList);
                        return;
                    }
                    ArrayList<Object> addList = new ArrayList<>(addList);
```

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java [hunk 3]
```diff
@@ -94,19 +97,21 @@ public void change(Event e, Object[] delta, Changer.ChangeMode mode) {
...
+                    addList.addAll(deltaList);
```
Comment (Romitou) [inline src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:102]: the arraylist is updated, but not the document
i think we should make a `Document#put` (like when the `addList` is null) to update the list

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java [hunk 4]
```diff
@@ -94,19 +97,21 @@ public void change(Event e, Object[] delta, Changer.ChangeMode mode) {
...
-                addList.addAll(deltaList);
-                break;
             case REMOVE:
-                List<Object> removeList = document.getList(value, Object.class);
-                if (removeList == null)
-                    return;
-                deltaList.forEach(removeList::remove);
-                break;
+                try {
+                    ArrayList<Object> removeList = new ArrayList<>(document.getList(value, Object.class));
```
Comment (Romitou) [inline src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:109]: same comments as for the `ADD`

**Review by Romitou — CHANGES_REQUESTED** [review]
good catch! this is indeed what was wrong
i have made a few remarks, do not hesitate to tell me what you think about it

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java (hunk 1 above)
Comment (Olyno) [reply src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:66]: ``getList`` returns an immutable list, so we must wrap it to avoid the ``UnsupportedOperation`` (refers to [this stackoverflow answer](https://stackoverflow.com/a/5755510/8845770)).
For the null check, I don't find it usefull in that case because you already have a try/catch, so we should use it more we can.

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java (hunk 2 above)
Comment (Olyno) [reply src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:101]: If there is any null somewhere, the catch will be triggered, so needn't to check if it's null or not.
Nice on for the ``Document#put`` 🦄 (my editor told me it was a dead code, I didn't check my bad)

**Comment by Olyno** [comment]
@EarthAgar Can you try [this artifact](https://github.com/Romitou/MongoSK/suites/2077283796/artifacts/42042315) please? Evertyhing should be fixed with this one (I hope 😁)

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java (hunk 1 above)
Comment (Romitou) [reply src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:66]: we never modify the immutable list here, we should only return a mutable array with the `List#toArray` method in my opinion
alright for the try/catch

File: src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java (hunk 2 above)
Comment (Romitou) [reply src/main/java/fr/romitou/mongosk/skript/expressions/documents/ExprDocumentValue.java:101]: the problem here is if the addList is null, nothing will happen due to the try/catch
however, if the list is null, so if the list doesn't exist in the document, we must create it

**Comment by Olyno** [comment]
Here is [the new artifact](https://github.com/Romitou/MongoSK/suites/2077981884/artifacts/42061605) to test ahahah

**Review by Romitou — APPROVED** [review]
Looks good to me! Thank you very much for your PR 😁

**Comment by EarthAgar** [comment]
Yup seems to work for me. I don't know what to call it but I'm getting a false check for a mongo documents tho. I wish I could explain it better but here is the error: 
image

**Comment by Olyno** [comment]
Well I would like to tell you it comes from the typing, but after got a look in types, you should not get this error, so... need to have a better look up ahah @EarthAgar

**Comment by EarthAgar** [comment]
> Well I would like to tell you it comes from the typing, but after got a look in types, you should not get this error, so... need to have a better look up ahah @EarthAgar

I'm somewhat confused on what you're trying to say but also I get that error from a condition in my script that has nothing to do with any mongo documents: `if (level of blast protection of event-slot ? 0) < 5:`

**Comment by EarthAgar** [comment]
Before using the artifacts that you gave me to test this wasn't an issue but it is now, so I can't really do anything to fix it. Here is a full snippet of my script so that you know I'm not trying to interact with any mongo documents. I will say that the original issue however is fixed and I can add to my list properly.

```
on inventory click:
	if type of player's cursor slot is slime ball:
		if custom model data of player's cursor slot is between 1000 and 1002:
			if "%type of event-item%" contains "helmet" or "chestplate" or "leggings" or "boots":
				cancel event
				if custom model data of player's cursor slot is 1000:
					if (level of blast protection of event-slot ? 0) < 5:
						enchant event-slot with "blast protection %(level of blast protection of event-slot ? 0) + 1%" parsed as enchantment type
						remove 1 of player's cursor slot from player's cursor slot
```

**Comment by Romitou** [comment]
I can indeed replicate this problem. I will investigate.

**Comment by EarthAgar** [comment]
> I can indeed replicate this problem. I will investigate.

Thank you <3

**Comment by Romitou** [comment]
The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).

**Comment by EarthAgar** [comment]
> The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).

Yup that fixed it but it seems to not understand the `first document where` expression anymore.
```
on join:
	set {_doc} to first document where "player" is player's uuid in {players-collection}
```
image

**Comment by EarthAgar** [comment]
> > The problem was that part of the syntax had become non-mandatory. I have made it obligatory, and everything should work again now! You can download the fixed version [here](https://github.com/Romitou/MongoSK/suites/2084700883/artifacts/42245455).
> 
> Yup that fixed it but it seems to not understand the `first document where` expression anymore.
> 
> ```
> on join:
> 	set {_doc} to first document where "player" is player's uuid in {players-collection}
> ```
> 
> image

I can't seem to `loop all documents` either

**Comment by EarthAgar** [comment]
Hey tt's been 5 days since the last response, are there any updates?

**Comment by Romitou** [comment]
Hello, the issue was resolved in the last update 4 days ago. 😄

**Comment by EarthAgar** [comment]
The initial issue was fixed but some of the syntax isn't working and it prevents me from using some of the syntax. I'm using the latest artifact linked here in this discussion but it seems to be missing some syntax such as `first document`. I already posted images and code of this issue earlier in the discussion.

**Comment by Romitou** [comment]
I thought version 1.1.3 would have solved your problem. Anyway, I am currently working very hard on version 2.0.0, which should be released in a few days. You will be able to upgrade and enjoy a fully fixed version.

**Comment by EarthAgar** [comment]
> I thought version 1.1.3 would have solved your problem. Anyway, I am currently working very hard on version 2.0.0, which should be released in a few days. You will be able to upgrade and enjoy a fully fixed version.

That sounds awesome, thank you for the quality plugin and support, I'm happy to wait!
